// Code generated by Kitex v0.3.0. DO NOT EDIT.

package userservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"rentWeb/kitex_gen/userapi"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetImgCaptcha(ctx context.Context, req *userapi.ImgCaptchaRequest, callOptions ...callopt.Option) (r *userapi.ImgCaptchaResponse, err error)
	SendSmsCaptcha(ctx context.Context, req *userapi.SmsCaptchaRequest, callOptions ...callopt.Option) (r *userapi.SmsCaptchaResponse, err error)
	RegisterUser(ctx context.Context, req *userapi.RegisterUserRequest, callOptions ...callopt.Option) (r *userapi.RegisterUserResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) GetImgCaptcha(ctx context.Context, req *userapi.ImgCaptchaRequest, callOptions ...callopt.Option) (r *userapi.ImgCaptchaResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetImgCaptcha(ctx, req)
}

func (p *kUserServiceClient) SendSmsCaptcha(ctx context.Context, req *userapi.SmsCaptchaRequest, callOptions ...callopt.Option) (r *userapi.SmsCaptchaResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendSmsCaptcha(ctx, req)
}

func (p *kUserServiceClient) RegisterUser(ctx context.Context, req *userapi.RegisterUserRequest, callOptions ...callopt.Option) (r *userapi.RegisterUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterUser(ctx, req)
}
