// Code generated by Kitex v0.3.0. DO NOT EDIT.

package homeservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"rentWeb/kitex_gen/homeapi"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetAreas(ctx context.Context, req *homeapi.AreaRequest, callOptions ...callopt.Option) (r *homeapi.AreaResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kHomeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kHomeServiceClient struct {
	*kClient
}

func (p *kHomeServiceClient) GetAreas(ctx context.Context, req *homeapi.AreaRequest, callOptions ...callopt.Option) (r *homeapi.AreaResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAreas(ctx, req)
}
